part of '../main.dart';

const List<BibleVersionOption> kSupportedBibleVersions = [
  BibleVersionOption(
    id: 128,
    code: 'NVI-S',
    name: 'Nueva Versión Internacional 2025',
  ),
  BibleVersionOption(
    id: 103,
    code: 'NBLA',
    name: 'Nueva Biblia de las Américas',
  ),
  BibleVersionOption(
    id: 127,
    code: 'NTV',
    name: 'Nueva Traducción Viviente',
    enabled: false,
  ),
  BibleVersionOption(
    id: 149,
    code: 'RVR1960',
    name: 'Reina Valera 1960',
    enabled: false,
  ),
  BibleVersionOption(id: 3291, code: 'VBL', name: 'Biblia Libre'),
];

const _kMasterBookKeys = <String, ({Set<String> aliases, bool singleChapter})>{
  'GEN': (aliases: {'Genesis', 'Gen', 'Gn', 'Ge'}, singleChapter: false),
  'EXO': (aliases: {'Exodus', 'Exo', 'Exodo', 'Ex'}, singleChapter: false),
  'LEV': (
    aliases: {'Leviticus', 'Lev', 'Levitico', 'Lv', 'Le'},
    singleChapter: false,
  ),
  'NUM': (
    aliases: {'Numbers', 'Num', 'Numeros', 'Nm', 'Nu'},
    singleChapter: false,
  ),
  'DEU': (
    aliases: {'Deuteronomy', 'Deut', 'Deuteronomio', 'Dt', 'De', 'Deu'},
    singleChapter: false,
  ),
  'JOS': (
    aliases: {'Joshua', 'Josh', 'Josue', 'Jos', 'Js'},
    singleChapter: false,
  ),
  'JDG': (
    aliases: {'Judges', 'Judg', 'Jueces', 'Jue', 'Jc', 'Ju'},
    singleChapter: false,
  ),
  'RUT': (aliases: {'Ruth', 'Rut', 'Ru', 'Rt'}, singleChapter: false),
  '1SA': (
    aliases: {
      '1 Samuel',
      '1Sam',
      '1Samuel',
      'I Samuel',
      'Primero Samuel',
      'Primero de Samuel',
      '1 Sam',
      '1 S',
      '1 Sm',
    },
    singleChapter: false,
  ),
  '2SA': (
    aliases: {
      '2 Samuel',
      '2Sam',
      '2Samuel',
      'II Samuel',
      'Segundo Samuel',
      'Segundo de Samuel',
      '2 Sam',
      '2 S',
      '2 Sm',
    },
    singleChapter: false,
  ),
  '1KI': (
    aliases: {
      '1 Kings',
      '1Kng',
      '1Kings',
      '1 Reyes',
      'I Reyes',
      'Primero Reyes',
      'Primero de Reyes',
      '1 R',
      '1 Rey',
      '1 Ry',
    },
    singleChapter: false,
  ),
  '2KI': (
    aliases: {
      '2 Kings',
      '2Kng',
      '2Kings',
      '2 Reyes',
      'II Reyes',
      'Segundo Reyes',
      'Segundo de Reyes',
      '2 R',
      '2 Rey',
      '2 Ry',
    },
    singleChapter: false,
  ),
  '1CH': (
    aliases: {
      '1 Chronicles',
      '1Chr',
      '1Chronicles',
      '1 Cronicas',
      'I Cronicas',
      'Primero Cronicas',
      'Primero de Cronicas',
      '1 Cro',
      '1 Cr',
    },
    singleChapter: false,
  ),
  '2CH': (
    aliases: {
      '2 Chronicles',
      '2Chr',
      '2Chronicles',
      '2 Cronicas',
      'II Cronicas',
      'Segundo Cronicas',
      'Segundo de Cronicas',
      '2 Cro',
      '2 Cr',
    },
    singleChapter: false,
  ),
  'EZR': (
    aliases: {'Ezra', 'Ezr', 'Esdras', 'Esd', 'Es'},
    singleChapter: false,
  ),
  'NEH': (
    aliases: {'Nehemiah', 'Neh', 'Nehemias', 'Nehm', 'Ne'},
    singleChapter: false,
  ),
  'EST': (aliases: {'Esther', 'Est', 'Ester', 'Et'}, singleChapter: false),
  'JOB': (aliases: {'Job', 'Jb'}, singleChapter: false),
  'PSA': (
    aliases: {'Psalms', 'Psalm', 'Salmos', 'Salmo', 'Sal', 'Ps'},
    singleChapter: false,
  ),
  'PRO': (
    aliases: {'Proverbs', 'Prov', 'Proverbios', 'Pr', 'Prv', 'Pro'},
    singleChapter: false,
  ),
  'ECC': (
    aliases: {'Ecclesiastes', 'Eccl', 'Eclesiastes', 'Ecl', 'Ec'},
    singleChapter: false,
  ),
  'SNG': (
    aliases: {
      'Song of Solomon',
      'Song',
      'SongOfSolomon',
      'Cantar',
      'Cantares',
      'Cnt',
      'Cant',
      'Ca',
      'Can',
    },
    singleChapter: false,
  ),
  'ISA': (aliases: {'Isaiah', 'Isa', 'Isaias', 'Is'}, singleChapter: false),
  'JER': (
    aliases: {'Jeremiah', 'Jer', 'Jeremias', 'Je', 'Jr'},
    singleChapter: false,
  ),
  'LAM': (
    aliases: {'Lamentations', 'Lam', 'Lamentaciones', 'La', 'Lm'},
    singleChapter: false,
  ),
  'EZK': (
    aliases: {'Ezekiel', 'Ezek', 'Ezequiel', 'Eze', 'Ez'},
    singleChapter: false,
  ),
  'DAN': (aliases: {'Daniel', 'Dan', 'Da', 'Dn'}, singleChapter: false),
  'HOS': (
    aliases: {'Hosea', 'Hos', 'Oseas', 'Os', 'Ose'},
    singleChapter: false,
  ),
  'JOL': (aliases: {'Joel', 'Jol', 'Jl'}, singleChapter: false),
  'AMO': (aliases: {'Amos', 'Am', 'Amo'}, singleChapter: false),
  'OBA': (
    aliases: {'Obadiah', 'Obad', 'Abdias', 'Abd', 'Ab'},
    singleChapter: true,
  ),
  'JON': (aliases: {'Jonah', 'Jon', 'Jonas', 'Jo'}, singleChapter: false),
  'MIC': (
    aliases: {'Micah', 'Mic', 'Miqueas', 'Miq', 'Mi'},
    singleChapter: false,
  ),
  'NAM': (aliases: {'Nahum', 'Nah', 'Naum', 'Na', 'Nau'}, singleChapter: false),
  'HAB': (aliases: {'Habakkuk', 'Hab', 'Habacuc', 'Hb'}, singleChapter: false),
  'ZEP': (
    aliases: {'Zephaniah', 'Zep', 'Ze', 'Sofonias', 'So', 'Sof', 'Sf'},
    singleChapter: false,
  ),
  'HAG': (
    aliases: {'Haggai', 'Hag', 'Ha', 'Hg', 'Hageo'},
    singleChapter: false,
  ),
  'ZEC': (
    aliases: {'Zechariah', 'Zech', 'Zacarias', 'Zac', 'Za'},
    singleChapter: false,
  ),
  'MAL': (
    aliases: {'Malachi', 'Mal', 'Ml', 'Mala', 'Mq'},
    singleChapter: false,
  ),
  'MAT': (
    aliases: {'Matthew', 'Matt', 'Mt', 'Mateo', 'San Mateo', 'Mat', 'Ma'},
    singleChapter: false,
  ),
  'MRK': (
    aliases: {'Mark', 'Mrk', 'Marcos', 'San Marcos', 'Mc', 'Mr', 'Mar', 'Marc'},
    singleChapter: false,
  ),
  'LUK': (
    aliases: {'Luke', 'Luk', 'Lc', 'Lucas', 'San Lucas', 'Luc'},
    singleChapter: false,
  ),
  'JHN': (
    aliases: {'John', 'Jhn', 'Juan', 'San Juan', 'Jn', 'Jua'},
    singleChapter: false,
  ),
  'ACT': (aliases: {'Acts', 'Hch', 'Hechos', 'Hc'}, singleChapter: false),
  'ROM': (
    aliases: {'Romans', 'Rom', 'Romanos', 'Ro', 'Rm'},
    singleChapter: false,
  ),
  '1CO': (
    aliases: {
      '1 Corinthians',
      '1Cor',
      '1Corinthians',
      '1 Corintios',
      'I Corintios',
      'Primera Corintios',
      'Primera de Corintios',
      '1 Cor',
      '1 Co',
    },
    singleChapter: false,
  ),
  '2CO': (
    aliases: {
      '2 Corinthians',
      '2Cor',
      '2Corinthians',
      '2 Corintios',
      'II Corintios',
      'Segunda Corintios',
      'Segunda de Corintios',
      '2 Cor',
      '2 Co',
    },
    singleChapter: false,
  ),
  'GAL': (
    aliases: {'Galatians', 'Gal', 'Galatas', 'Ga', 'Gl'},
    singleChapter: false,
  ),
  'EPH': (
    aliases: {'Ephesians', 'Eph', 'Efe', 'Efesios', 'Ef'},
    singleChapter: false,
  ),
  'PHP': (
    aliases: {'Philippians', 'Phil', 'Filipenses', 'Flp', 'Fi', 'Fil'},
    singleChapter: false,
  ),
  'COL': (
    aliases: {'Colossians', 'Col', 'Colosenses', 'Co'},
    singleChapter: false,
  ),
  '1TH': (
    aliases: {
      '1 Thessalonians',
      '1Thes',
      '1Tes',
      '1Thessalonians',
      '1 Tesalonicenses',
      'I Tesalonicenses',
      'Primera Tesalonicenses',
      'Primera de Tesalonicenses',
      '1 Tes',
      '1 Ts',
    },
    singleChapter: false,
  ),
  '2TH': (
    aliases: {
      '2 Thessalonians',
      '2Thes',
      '2Tes',
      '2Thessalonians',
      '2 Tesalonicenses',
      'II Tesalonicenses',
      'Segunda Tesalonicenses',
      'Segunda de Tesalonicenses',
      '2 Tes',
      '2 Ts',
    },
    singleChapter: false,
  ),
  '1TI': (
    aliases: {
      '1 Timothy',
      '1Tim',
      '1Timothy',
      '1 Timoteo',
      'I Timoteo',
      'Primera Timoteo',
      'Primera de Timoteo',
      '1 Tim',
      '1 Ti',
      '1Tm',
    },
    singleChapter: false,
  ),
  '2TI': (
    aliases: {
      '2 Timothy',
      '2Tim',
      '2Timothy',
      '2 Timoteo',
      'II Timoteo',
      'Segunda Timoteo',
      'Segunda de Timoteo',
      '2 Tim',
      '2 Ti',
      '2Tm',
    },
    singleChapter: false,
  ),
  'TIT': (aliases: {'Titus', 'Tit', 'Tito', 'Ti'}, singleChapter: false),
  'PHM': (aliases: {'Philemon', 'Phm', 'Filemon', 'Flm'}, singleChapter: true),
  'HEB': (aliases: {'Hebrews', 'Heb', 'Hebreos', 'He'}, singleChapter: false),
  'JAS': (aliases: {'James', 'Jam', 'Santiago', 'Stg'}, singleChapter: false),
  '1PE': (
    aliases: {
      '1 Peter',
      '1Pet',
      '1Peter',
      '1 Pedro',
      'I Pedro',
      'Primera Pedro',
      'Primera de Pedro',
      '1 P',
    },
    singleChapter: false,
  ),
  '2PE': (
    aliases: {
      '2 Peter',
      '2Pet',
      '2Peter',
      '2 Pedro',
      'II Pedro',
      'Segunda Pedro',
      'Segunda de Pedro',
      '2 P',
    },
    singleChapter: false,
  ),
  '1JN': (
    aliases: {
      '1 John',
      '1Jn',
      '1John',
      '1 Juan',
      'I Juan',
      'Primera Juan',
      'Primera de Juan',
      '1 Jn',
    },
    singleChapter: false,
  ),
  '2JN': (
    aliases: {
      '2 John',
      '2Jn',
      '2John',
      '2 Juan',
      'II Juan',
      'Segunda Juan',
      'Segunda de Juan',
      '2 Jn',
    },
    singleChapter: true,
  ),
  '3JN': (
    aliases: {
      '3 John',
      '3Jn',
      '3John',
      '3 Juan',
      'III Juan',
      'Tercera Juan',
      'Tercera de Juan',
      '3 Jn',
    },
    singleChapter: true,
  ),
  'JUD': (aliases: {'Jude', 'Jud', 'Judas', 'Juda', 'Jd'}, singleChapter: true),
  'REV': (
    aliases: {'Revelation', 'Rev', 'Apocalipsis', 'Apoc', 'Ap', 'Apo'},
    singleChapter: false,
  ),
};

// Canonical Protestant 66-book chapter counts.
const _kChapterCountByUsfmBook = <String, int>{
  'GEN': 50,
  'EXO': 40,
  'LEV': 27,
  'NUM': 36,
  'DEU': 34,
  'JOS': 24,
  'JDG': 21,
  'RUT': 4,
  '1SA': 31,
  '2SA': 24,
  '1KI': 22,
  '2KI': 25,
  '1CH': 29,
  '2CH': 36,
  'EZR': 10,
  'NEH': 13,
  'EST': 10,
  'JOB': 42,
  'PSA': 150,
  'PRO': 31,
  'ECC': 12,
  'SNG': 8,
  'ISA': 66,
  'JER': 52,
  'LAM': 5,
  'EZK': 48,
  'DAN': 12,
  'HOS': 14,
  'JOL': 3,
  'AMO': 9,
  'OBA': 1,
  'JON': 4,
  'MIC': 7,
  'NAM': 3,
  'HAB': 3,
  'ZEP': 3,
  'HAG': 2,
  'ZEC': 14,
  'MAL': 4,
  'MAT': 28,
  'MRK': 16,
  'LUK': 24,
  'JHN': 21,
  'ACT': 28,
  'ROM': 16,
  '1CO': 16,
  '2CO': 13,
  'GAL': 6,
  'EPH': 6,
  'PHP': 4,
  'COL': 4,
  '1TH': 5,
  '2TH': 3,
  '1TI': 6,
  '2TI': 4,
  'TIT': 3,
  'PHM': 1,
  'HEB': 13,
  'JAS': 5,
  '1PE': 5,
  '2PE': 3,
  '1JN': 5,
  '2JN': 1,
  '3JN': 1,
  'JUD': 1,
  'REV': 22,
};

int? _maxChapterForUsfmBook(String usfmBookCode) {
  return _kChapterCountByUsfmBook[usfmBookCode];
}

bool _isValidChapterForUsfmBook({
  required String usfmBookCode,
  required String chapter,
}) {
  final maxChapter = _maxChapterForUsfmBook(usfmBookCode);
  if (maxChapter == null) return false;
  final chapterNumber = int.tryParse(chapter);
  if (chapterNumber == null) return false;
  return chapterNumber >= 1 && chapterNumber <= maxChapter;
}
